name 'elk'
maintainer 'XPeppers'
maintainer_email 'devops@xpeppers.com'
license 'all_rights'
description 'Installs/Configures elk'
long_description 'Installs/Configures elk'
version '0.1.0'

depends 'java'
depends 'elasticsearch', '~> 2.1.1'
depends 'tar', '~> 0.7.0'
