begin
  require './config.rb'
rescue LoadError
  require '../../../config.rb'
end

Vagrant.configure('2') do |config|

  config.vm.box = 'bento/centos-7.1'
  config.vm.hostname = 'elk-berkshelf'
  config.vm.box_check_update = false
  config.vm.network :private_network, ip: '192.168.33.100'

  config.berkshelf.enabled = false

  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end

  if custom_config["proxy"]
    config.proxy.no_proxy = "localhost,127.0.0.1,192.168.33.*"
    config.proxy.http = custom_config["proxy"]
    config.proxy.https = custom_config["proxy"]
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.auto_detect = false
    config.cache.enable :yum
    config.cache.enable :gem
    config.cache.enable :chef_gem
    config.cache.enable :generic, { :cache_dir => "/var/chef/cache" }
  end

end
